---
blank_issues_enabled: false
contact_links:
  - name: Architectural Design Patterns in SwiftUI Community Support
    url: https://github.com/developer-academy-unina/Workshop-Architectural-Design-Patterns-in-SwiftUI/discussions
    about: Please ask and answer questions here.
